#! /bin/bash
#
##АВТОСТАРТ
sxhkd &
numlockx &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
polybar &
lxpolkit &
setxkbmap -option grp:alt_shift_toggle us,ru &
xset s off -dpms
#
##ВОРКСПЕЙСЫ
#
bspc monitor  -d  1 2 3 4 7 8 9 0  
#
##РАМКИ И ГАПСЫ
bspc config window_gap           0 
###bspc config normal_border_color  "#000000"
###bspc config active_border_color  "#000000"
##bspc config focused_border_color "#d8dee9"
#
##ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНАЫ
bspc config presel_feedback_color "fd2e59"
#
##ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
##bspc config window_gap $gap;
##bspc config top_padding -$(($gap+2))
##bspc config left_padding -$(($gap+2))
##bspc config right_padding -$(($gap+4))
##bspc config bottom_padding $(($PANEL_HEIGHT-$gap))
#
##КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5
#
##ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super
#
##РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	    false  
#
##ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
#
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true 
#
#
#
##СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
##bspc config automatic_scheme	spiral
#
##ПРАВИЛА ОКОН
##bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off 
